// Render360 v47/v48 UI — import reliability, responsive profile UI and Xbox 360-era gamerpics.
const $=id=>document.getElementById(id);
// R360_SEGMENTED_BOOT_V49: profile styling follows the profile module.
if(!document.querySelector('link[data-r360-ui="v47"]')){const link=document.createElement('link');link.rel='stylesheet';link.href='./styles/v47.css';link.dataset.r360Ui='v47';document.head.appendChild(link);}
const PROFILE_KEY='render360.profile.v1';
const AVATARS=[
['orbit',`<svg viewBox="0 0 64 64" aria-hidden="true"><defs><linearGradient id="a" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#57d4ff"/><stop offset="1" stop-color="#6e5cff"/></linearGradient></defs><circle cx="32" cy="32" r="30" fill="#101116"/><circle cx="32" cy="32" r="18" fill="none" stroke="url(#a)" stroke-width="5"/><circle cx="49" cy="22" r="5" fill="#fff"/><path d="M17 42c10 7 22 7 31-1" fill="none" stroke="#fff" stroke-width="4" stroke-linecap="round"/></svg>`],
['city',`<svg viewBox="0 0 64 64" aria-hidden="true"><defs><linearGradient id="b" x1="0" y1="1" x2="1" y2="0"><stop stop-color="#ff7a4a"/><stop offset="1" stop-color="#9d4edd"/></linearGradient></defs><rect width="64" height="64" rx="32" fill="#111216"/><path d="M10 49h44M15 49V28h11v21m4 0V18h12v31m4 0V32h7v17" stroke="url(#b)" stroke-width="4" fill="none"/><path d="M20 34h2m13-8h2m-2 8h2" stroke="#fff" stroke-width="3" stroke-linecap="round"/></svg>`],
['racer',`<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="30" fill="#141414"/><circle cx="32" cy="32" r="18" fill="none" stroke="#ffd60a" stroke-width="5"/><circle cx="32" cy="32" r="5" fill="#fff"/><path d="M32 14v13M17 39l12-5m18 5-12-5" stroke="#fff" stroke-width="4" stroke-linecap="round"/></svg>`],
['hourglass',`<svg viewBox="0 0 64 64" aria-hidden="true"><defs><linearGradient id="c" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#7dd3fc"/><stop offset="1" stop-color="#fde68a"/></linearGradient></defs><circle cx="32" cy="32" r="30" fill="#12151c"/><path d="M20 14h24M20 50h24M23 16c0 10 6 12 9 16-3 4-9 6-9 16m18-32c0 10-6 12-9 16 3 4 9 6 9 16" stroke="url(#c)" stroke-width="4" fill="none" stroke-linecap="round"/><path d="M27 39h10l-5 6z" fill="#fff"/></svg>`],
['arcade',`<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="30" fill="#101315"/><path d="M16 26c2-8 8-12 16-12s14 4 16 12l5 18c1 5-5 8-8 4l-7-8H26l-7 8c-3 4-9 1-8-4z" fill="#1f2937" stroke="#30d158" stroke-width="3"/><path d="M22 30h8m-4-4v8" stroke="#fff" stroke-width="3" stroke-linecap="round"/><circle cx="40" cy="28" r="2.5" fill="#ff453a"/><circle cx="46" cy="33" r="2.5" fill="#0a84ff"/></svg>`],
['neon',`<svg viewBox="0 0 64 64" aria-hidden="true"><defs><linearGradient id="d" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#30d158"/><stop offset=".5" stop-color="#0a84ff"/><stop offset="1" stop-color="#ff375f"/></linearGradient></defs><circle cx="32" cy="32" r="30" fill="#0b0c10"/><path d="M17 43 27 18h10l10 25-15-8z" fill="none" stroke="url(#d)" stroke-width="5" stroke-linejoin="round"/><circle cx="32" cy="32" r="4" fill="#fff"/></svg>`]
];
// Real Xbox 360 title gamerpics, linked from the public xtitles/xboxgamer.pics archive rather than copied into Render360.
// R360_XBOX_HERO_ART_V50: action-oriented Xbox 360 gamerpics (GTA IV + Halo 3).
const XBOX360_GAMERPICS=[
  ...Array.from({length:9},(_,i)=>`https://raw.githubusercontent.com/birabittoh/xtitles/refs/heads/main/titles/545407f2/${(0x28000+i).toString(16)}.png`),
  ...Array.from({length:9},(_,i)=>`https://raw.githubusercontent.com/birabittoh/xtitles/refs/heads/main/titles/4d5307e6/${(0x28000+i).toString(16)}.png`),
];
function loadProfile(){try{return {...JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')}}catch{return {}}}
function saveProfile(next){try{localStorage.setItem(PROFILE_KEY,JSON.stringify(next))}catch{}}
function randomUsername(){const a=['Nova','Pixel','Turbo','Neon','Arcade','Orbit','Vector','Rapid','Shadow','Retro'],b=['Pilot','Rider','Player','Runner','Knight','Drift','Byte','Quest','Wave','Core'];return `${a[Math.floor(Math.random()*a.length)]}${b[Math.floor(Math.random()*b.length)]}${String(Math.floor(Math.random()*100)).padStart(2,'0')}`;}
function avatarMarkup(p){if(p.photoData)return `<img src="${p.photoData}" alt="" draggable="false">`;if(p.gamerpicUrl)return `<img src="${p.gamerpicUrl}" alt="Xbox 360 gamerpic" draggable="false" referrerpolicy="no-referrer">`;return (AVATARS.find(([id])=>id===(p.avatar||'orbit'))||AVATARS[0])[1];}
function profileState(){const p=loadProfile();if(!p.username){p.username=randomUsername();p.avatar='orbit';saveProfile(p)}return p;}
function resizeProfilePhoto(file){return new Promise((resolve,reject)=>{if(!file||!/^image\//.test(file.type))return reject(new Error('Choose an image file.'));const reader=new FileReader();reader.onerror=()=>reject(new Error('Unable to read that image.'));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('Unable to decode that image.'));img.onload=()=>{const size=160,c=document.createElement('canvas');c.width=c.height=size;const ctx=c.getContext('2d'),scale=Math.max(size/img.width,size/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(size-w)/2,(size-h)/2,w,h);resolve(c.toDataURL('image/jpeg',.82));};img.src=reader.result;};reader.readAsDataURL(file);});}
function updateProfileChrome(){const p=profileState(),button=$('profileButton');if(!button)return;button.innerHTML=`<span class="r360-profile-nav-avatar">${avatarMarkup(p)}</span>`;button.title=p.username;button.setAttribute('aria-label',`Profile: ${p.username}`);}
function profileNotice(text,kind=''){const el=$('r360ProfileNotice');if(el){el.textContent=text;el.dataset.kind=kind}}
async function attemptAppleSignIn(){const cfg=globalThis.Render360AppleAuthConfig;if(!cfg?.clientId||!cfg?.redirectURI){profileNotice('Apple account sync needs a Render360 Apple Services ID and secure server callback before it can be enabled.','info');return}try{if(!globalThis.AppleID?.auth){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js';s.onload=resolve;s.onerror=()=>reject(new Error('Apple Sign in could not load.'));document.head.appendChild(s)})}AppleID.auth.init({clientId:cfg.clientId,scope:'name email',redirectURI:cfg.redirectURI,usePopup:true,state:cfg.state||crypto.randomUUID?.()||String(Date.now()),nonce:cfg.nonce||crypto.randomUUID?.()||String(Date.now())});const response=await AppleID.auth.signIn();if(typeof cfg.onCredential==='function')await cfg.onCredential(response);profileNotice('Apple returned a credential. Render360 will only mark the account connected after your server verifies it.','success')}catch(error){profileNotice(error?.error||error?.message||'Apple sign-in was cancelled.','error')}}
function enhanceProfile(){const sheet=$('profileSheet');if(!sheet||sheet.dataset.r360V48==='1')return;sheet.dataset.r360V48='1';document.body.appendChild(sheet);const p=profileState(),safe=String(p.username).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');sheet.innerHTML=`<div class="sheet-handle"></div><div class="sheet-head"><b>Render360 Profile</b></div><div class="sheet-content r360-profile-v47-content"><div id="r360ProfileHero" class="r360-profile-avatar r360-profile-avatar-v47">${avatarMarkup(p)}</div><label class="r360-profile-field"><span>Username</span><input id="r360ProfileUsername" maxlength="20" autocomplete="off" spellcheck="false" value="${safe}"></label><div class="r360-avatar-heading">Xbox 360 Action Gamerpics</div><div id="r360XboxAvatarGrid" class="r360-avatar-grid r360-xbox-avatar-grid">${XBOX360_GAMERPICS.map((url,i)=>`<button type="button" data-gamerpic="${url}" class="r360-avatar-choice${p.gamerpicUrl===url&&!p.photoData?' selected':''}" aria-label="Use Xbox 360 gamerpic ${i+1}"><img src="${url}" alt="" loading="lazy" referrerpolicy="no-referrer"></button>`).join('')}</div><div class="r360-avatar-heading r360-render-avatar-heading">Render360 Icons</div><div id="r360AvatarGrid" class="r360-avatar-grid">${AVATARS.map(([id,svg])=>`<button type="button" data-avatar="${id}" class="r360-avatar-choice${p.avatar===id&&!p.photoData&&!p.gamerpicUrl?' selected':''}" aria-label="Use ${id} avatar">${svg}</button>`).join('')}</div><input id="r360ProfilePhotoInput" type="file" accept="image/*" hidden><button id="r360ProfilePhoto" class="r360-profile-inline-action" type="button">Choose Photo</button><button id="r360AppleSignIn" class="r360-apple-button" type="button"><span class="r360-apple-mark"></span><span>Continue with Apple</span></button><div id="r360ProfileNotice" class="r360-profile-notice">Classic GTA IV and Halo 3 Xbox 360 gamerpics load from the public xtitles archive; your selection is saved on this device.</div></div><button id="profileSettingsShortcut" class="sheet-action" type="button">Settings</button><button id="profileDone" class="sheet-action primary-action" type="button">Done</button>`;
const commit=()=>{const next=profileState(),value=String($('r360ProfileUsername')?.value||'').trim().replace(/[^A-Za-z0-9 _.-]/g,'').slice(0,20);next.username=value||randomUsername();saveProfile(next);$('r360ProfileUsername').value=next.username;updateProfileChrome()};
$('r360ProfileUsername')?.addEventListener('change',commit);$('r360ProfileUsername')?.addEventListener('keydown',e=>{if(e.key==='Enter'){commit();e.currentTarget.blur()}});
$('r360AvatarGrid')?.addEventListener('click',e=>{const btn=e.target.closest('[data-avatar]');if(!btn)return;const next=profileState();next.avatar=btn.dataset.avatar;delete next.photoData;delete next.gamerpicUrl;saveProfile(next);$('r360ProfileHero').innerHTML=avatarMarkup(next);document.querySelectorAll('.r360-avatar-choice').forEach(x=>x.classList.toggle('selected',x===btn));updateProfileChrome()});
$('r360XboxAvatarGrid')?.addEventListener('click',e=>{const btn=e.target.closest('[data-gamerpic]');if(!btn)return;const next=profileState();next.gamerpicUrl=btn.dataset.gamerpic;delete next.photoData;saveProfile(next);$('r360ProfileHero').innerHTML=avatarMarkup(next);document.querySelectorAll('.r360-avatar-choice').forEach(x=>x.classList.toggle('selected',x===btn));updateProfileChrome();profileNotice('Xbox 360 gamerpic selected.','success')});
$('r360ProfilePhoto')?.addEventListener('click',()=>{$('r360ProfilePhotoInput').value='';$('r360ProfilePhotoInput').click()});$('r360ProfilePhotoInput')?.addEventListener('change',async e=>{try{const photoData=await resizeProfilePhoto(e.target.files?.[0]),next=profileState();next.photoData=photoData;delete next.gamerpicUrl;saveProfile(next);$('r360ProfileHero').innerHTML=avatarMarkup(next);document.querySelectorAll('.r360-avatar-choice').forEach(x=>x.classList.remove('selected'));updateProfileChrome();profileNotice('Profile photo saved on this device.','success')}catch(error){profileNotice(error.message,'error')}});$('r360AppleSignIn')?.addEventListener('click',attemptAppleSignIn);$('profileDone')?.addEventListener('click',()=>{$('profileSheet').classList.add('hidden');$('scrim')?.classList.add('hidden')});$('profileSettingsShortcut')?.addEventListener('click',()=>{$('profileSheet').classList.add('hidden');$('scrim')?.classList.add('hidden');$('settingsButton')?.click()});updateProfileChrome();}
function bindReliableImport(){for(const id of ['importButton','emptyImportButton']){const button=$(id);if(!button||button.dataset.r360ImportV47==='1')continue;button.dataset.r360ImportV47='1';button.addEventListener('click',event=>{const input=$('importInput');if(!input)return;event.preventDefault();event.stopImmediatePropagation();input.value='';try{if(typeof input.showPicker==='function')input.showPicker();else input.click()}catch{input.click()}},true)}}
function keepImportAvailable(){const ready=$('runtimeSyncStatus')?.classList.contains('ready')||/^Emulator ready/i.test($('runtimeSyncText')?.textContent||'');if(!ready)return;for(const id of ['importButton','emptyImportButton']){const b=$(id);if(b){b.disabled=false;b.removeAttribute('disabled');b.removeAttribute('aria-disabled')}}}
function simplifySettings(){const reset=$('resetAppSettings');if(reset){reset.querySelector('span')?.replaceChildren('Reset Settings');reset.classList.add('r360-reset-settings')}const settings=$('appSettingsView');if(!settings)return;const titles=[...settings.querySelectorAll('.group-title')],runtimeContract=titles.find(x=>x.textContent.trim()==='Runtime Contract');if(runtimeContract){const group=runtimeContract.nextElementSibling,sync=()=>{const dev=!!$('appDeveloper')?.checked;runtimeContract.classList.toggle('r360-dev-only-hidden',!dev);group?.classList.toggle('r360-dev-only-hidden',!dev)};sync();$('appDeveloper')?.addEventListener('change',sync)}}
function syncDeveloperConsoleVisibility(){const inRuntime=!$('runtimeView')?.classList.contains('hidden'),fab=$('r360RuntimeConsole');if(fab){fab.classList.toggle('r360-runtime-only-hidden',!inRuntime);fab.setAttribute('aria-hidden',inRuntime?'false':'true')}const settingsEntry=$('appDeveloperConsoleButton');if(settingsEntry)settingsEntry.classList.add('r360-runtime-only-hidden');if(!inRuntime&&!$('r360DevConsole')?.classList.contains('hidden'))globalThis.render360DeveloperConsole?.close?.()}
function bootV47(){bindReliableImport();enhanceProfile();simplifySettings();keepImportAvailable();syncDeveloperConsoleVisibility();updateProfileChrome();const observer=new MutationObserver(()=>{bindReliableImport();enhanceProfile();keepImportAvailable();syncDeveloperConsoleVisibility()});observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class','data-state']});setInterval(()=>{keepImportAvailable();syncDeveloperConsoleVisibility()},700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootV47,{once:true});else bootV47();
