#!/usr/bin/env python3
"""Generate Render360 kernel export tables from upstream Xenia.

Xenia's xboxkrnl_table.inc and xam_table.inc are the source of truth for Xbox
360 kernel export ordinals. This script turns them into:

  src/xenia_web_bootstrap/kernel_export_ordinals.h
      constexpr ordinals used by the native WASM kernel service layer, so C++
      dispatch never hard-codes a hand-typed ordinal.
  render360-kernel-export-names.mjs
      ordinal -> name/kind maps used by browser diagnostics, the headless title
      runner and tests, so a blocker reads "HalReturnToFirmware" rather than
      "xboxkrnl ordinal 0x28".

Usage: python3 tools/generate-kernel-export-tables.py [--check]
Requires ./fetch-xenia.sh to have populated upstream/xenia.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
XENIA = ROOT / "upstream" / "xenia" / "src" / "xenia" / "kernel"
TABLES = (
    ("xboxkrnl", "xboxkrnl.exe", XENIA / "xboxkrnl" / "xboxkrnl_table.inc"),
    ("xam", "xam.xex", XENIA / "xam" / "xam_table.inc"),
)
HEADER_OUT = ROOT / "src" / "xenia_web_bootstrap" / "kernel_export_ordinals.h"
JS_OUT = ROOT / "render360-kernel-export-names.mjs"
ROW = re.compile(r"XE_EXPORT\(\s*(\w+)\s*,\s*(0x[0-9A-Fa-f]+)\s*,\s*(\w+)\s*,\s*(\w+)\s*\)")


def parse(path: Path):
    rows = []
    seen = set()
    for module, ordinal, name, kind in ROW.findall(path.read_text()):
        value = int(ordinal, 16)
        if value in seen:
            raise SystemExit(f"duplicate ordinal 0x{value:X} in {path}")
        seen.add(value)
        rows.append((value, name, "variable" if kind == "kVariable" else "function"))
    if not rows:
        raise SystemExit(f"no exports parsed from {path}")
    return rows


def render_header(tables) -> str:
    out = [
        "// Generated by tools/generate-kernel-export-tables.py from upstream Xenia",
        "// xboxkrnl_table.inc / xam_table.inc. Do not edit by hand.",
        "#ifndef RENDER360_XENIA_WEB_BOOTSTRAP_KERNEL_EXPORT_ORDINALS_H_",
        "#define RENDER360_XENIA_WEB_BOOTSTRAP_KERNEL_EXPORT_ORDINALS_H_",
        "",
        "#include <cstdint>",
        "",
        "namespace render360::xenia_web::ordinals {",
    ]
    for prefix, _, rows in tables:
        out.append("")
        out.append(f"namespace {prefix} {{")
        for value, name, _ in rows:
            out.append(f"constexpr uint32_t {name} = 0x{value:04X};")
        out.append(f"}}  // namespace {prefix}")
    out += [
        "",
        "}  // namespace render360::xenia_web::ordinals",
        "",
        "#endif",
        "",
    ]
    return "\n".join(out)


def render_js(tables) -> str:
    out = [
        "// Generated by tools/generate-kernel-export-tables.py from upstream Xenia",
        "// xboxkrnl_table.inc / xam_table.inc. Do not edit by hand.",
        "// Each entry is [ordinal, name, kind] where kind is 'function' or 'variable'.",
        "",
    ]
    for prefix, module_name, rows in tables:
        body = ",".join(f"[{value},'{name}','{kind[0]}']" for value, name, kind in rows)
        out.append(f"const {prefix.upper()}_ROWS=[{body}];")
    out += [
        "",
        "const expand=rows=>new Map(rows.map(([ordinal,name,kind])=>[ordinal,{ordinal,name,kind:kind==='v'?'variable':'function'}]));",
        "export const XBOXKRNL_EXPORTS=expand(XBOXKRNL_ROWS);",
        "export const XAM_EXPORTS=expand(XAM_ROWS);",
        "const MODULE_TABLES=new Map([['xboxkrnl.exe',XBOXKRNL_EXPORTS],['xam.xex',XAM_EXPORTS],[1,XBOXKRNL_EXPORTS],[2,XAM_EXPORTS]]);",
        "",
        "/** Look up an Xbox 360 kernel export by module name/id and ordinal. */",
        "export function kernelExport(module,ordinal){",
        "  const table=MODULE_TABLES.get(typeof module==='string'?module.toLowerCase():module);",
        "  return table?.get(Number(ordinal)>>>0)??null;",
        "}",
        "",
        "/** Human-readable export name, falling back to module!0xORDINAL. */",
        "export function kernelExportName(module,ordinal){",
        "  const found=kernelExport(module,ordinal);",
        "  if(found)return found.name;",
        "  const label=typeof module==='number'?(module===1?'xboxkrnl.exe':module===2?'xam.xex':`module${module}`):String(module);",
        "  return `${label}!0x${(Number(ordinal)>>>0).toString(16).toUpperCase()}`;",
        "}",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    check = "--check" in sys.argv[1:]
    tables = []
    for prefix, module_name, path in TABLES:
        if not path.exists():
            raise SystemExit(f"missing {path}; run ./fetch-xenia.sh first")
        tables.append((prefix, module_name, parse(path)))
    outputs = {HEADER_OUT: render_header(tables), JS_OUT: render_js(tables)}
    stale = []
    for path, text in outputs.items():
        if check:
            if not path.exists() or path.read_text() != text:
                stale.append(path)
        else:
            path.write_text(text)
    if stale:
        for path in stale:
            print(f"stale generated kernel export table: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    counts = ", ".join(f"{prefix}={len(rows)}" for prefix, _, rows in tables)
    print(f"kernel export tables {'verified' if check else 'written'}: {counts}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
